/**
 * deploy-mint.ts — One-time script to deploy the SELAH SPL Token-2022 mint to Solana.
 *
 * Prerequisites:
 *   1. Set SELAH_MINT_KEYPAIR in .env.local (generated by generate-keypair.ts)
 *   2. Fund the mint authority wallet with at least 0.1 SOL on devnet:
 *        solana airdrop 1 <MINT_AUTHORITY_PUBKEY> --url devnet
 *
 * Usage:
 *   npx ts-node scripts/deploy-mint.ts
 *
 * Output:
 *   Prints the mint address — copy it into EXPO_PUBLIC_SELAH_MINT_ADDRESS in .env.local
 */

import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

import {
  Connection,
  Keypair,
  LAMPORTS_PER_SOL,
  clusterApiUrl,
} from '@solana/web3.js';
import {
  createMint,
  TOKEN_2022_PROGRAM_ID,
} from '@solana/spl-token';

async function main() {
  const raw = process.env.SELAH_MINT_KEYPAIR;
  if (!raw) {
    console.error('ERROR: SELAH_MINT_KEYPAIR is not set in .env.local');
    process.exit(1);
  }

  let mintAuthority: Keypair;
  try {
    mintAuthority = Keypair.fromSecretKey(Uint8Array.from(JSON.parse(raw)));
  } catch {
    console.error('ERROR: Invalid SELAH_MINT_KEYPAIR format. Expected JSON number array.');
    process.exit(1);
  }

  const network = (process.env.EXPO_PUBLIC_SOLANA_NETWORK ?? 'devnet') as
    | 'devnet'
    | 'mainnet-beta';
  const rpc = process.env.EXPO_PUBLIC_SOLANA_RPC ?? clusterApiUrl(network);

  console.log(`\nDeploying SELAH mint on ${network}...`);
  console.log(`Mint authority: ${mintAuthority.publicKey.toBase58()}`);

  const connection = new Connection(rpc, 'confirmed');

  // Check balance
  const balance = await connection.getBalance(mintAuthority.publicKey);
  const sol = balance / LAMPORTS_PER_SOL;
  console.log(`Balance: ${sol.toFixed(6)} SOL`);

  if (sol < 0.01) {
    console.error(
      '\nERROR: Insufficient SOL. Fund the mint authority wallet first:',
    );
    console.error(`  solana airdrop 1 ${mintAuthority.publicKey.toBase58()} --url ${network}`);
    process.exit(1);
  }

  console.log('\nCreating SPL Token-2022 mint (0 decimals, soul-bound)...');

  const mintAddress = await createMint(
    connection,
    mintAuthority,            // payer
    mintAuthority.publicKey,  // mint authority
    null,                     // no freeze authority
    0,                        // 0 decimals (whole tokens only)
    undefined,
    { commitment: 'confirmed' },
    TOKEN_2022_PROGRAM_ID,
  );

  console.log('\n✓ SELAH mint deployed successfully!');
  console.log(`\nMint address: ${mintAddress.toBase58()}`);
  console.log('\nAdd this to .env.local:');
  console.log(`  EXPO_PUBLIC_SELAH_MINT_ADDRESS=${mintAddress.toBase58()}`);
  console.log('\nVerify on Solana Explorer:');
  console.log(
    `  https://explorer.solana.com/address/${mintAddress.toBase58()}?cluster=${network}`,
  );
}

main().catch((err) => {
  console.error('\nDeploy failed:', err);
  process.exit(1);
});
